/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface ConfigResponse {
  dojo_token: string;
  distribution_schedule: [number, number, Uint128][];
  staking_token: string;
  [k: string]: unknown;
}
export type Cw20HookMsg = {
  bond: {
    [k: string]: unknown;
  };
};
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  unbond: {
    amount: Uint128;
    [k: string]: unknown;
  };
} | {
  withdraw: {
    [k: string]: unknown;
  };
} | {
  migrate_staking: {
    new_staking_contract: string;
    [k: string]: unknown;
  };
};
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  dojo_token: string;
  distribution_schedule: [number, number, Uint128][];
  staking_token: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {
    [k: string]: unknown;
  };
} | {
  state: {
    block_height?: number | null;
    [k: string]: unknown;
  };
} | {
  staker_info: {
    block_height?: number | null;
    staker: string;
    [k: string]: unknown;
  };
};
export type Decimal = string;
export interface StakerInfoResponse {
  bond_amount: Uint128;
  pending_reward: Uint128;
  reward_index: Decimal;
  staker: string;
  [k: string]: unknown;
}
export interface StateResponse {
  global_reward_index: Decimal;
  last_distributed: number;
  total_bond_amount: Uint128;
  [k: string]: unknown;
}