/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface ConfigResponse {
  admin: Addr;
  allow_claim: boolean;
  end_time: number;
  offering_amount: Uint128;
  offering_token: Addr;
  raising_amount: Uint128;
  raising_denom: string;
  start_time: number;
  total_amount: Uint128;
}
export type ExecuteMsg = {
  deposit: {
    amount: Uint128;
  };
} | {
  harvest: {};
} | {
  update_config: {
    end_time?: number | null;
    offering_amount?: Uint128 | null;
    offering_token?: Addr | null;
    raising_amount?: Uint128 | null;
    raising_denom?: string | null;
    start_time?: number | null;
  };
} | {
  final_withdraw: {
    offer_amount: Uint128;
    raise_amount: Uint128;
  };
} | {
  flip_allow_claim: {};
};
export interface InstantiateMsg {
  admin: Addr;
  end_time: number;
  offering_amount: Uint128;
  offering_token: Addr;
  raising_amount: Uint128;
  raising_denom: string;
  start_time: number;
}
export type QueryMsg = {
  get_user: {
    address: Addr;
  };
} | {
  get_total_amount: {};
} | {
  config: {};
} | {
  is_claiming_allowed: {};
};